export const AUTH_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
};

export const RECIPE_ACTIONS = {
  LOAD_MORE_SUCCESS: 'LOAD_MORE_SUCCESS',
  LIKE_RECIPE: 'LIKE_RECIPE',
  UNLIKE_RECIPE: 'UNLIKE_RECIPE',
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  ADD_COMMENT: 'ADD_COMMENT',
  ROLLBACK_COMMENT: 'ROLLBACK_COMMENT',
  LOAD_FROM_STORAGE: 'LOAD_FROM_STORAGE',
};

export const PLANNER_ACTIONS = {
  ADD_TO_DAY: 'ADD_TO_DAY',
  REMOVE_FROM_DAY: 'REMOVE_FROM_DAY',
  CLEAR_DAY: 'CLEAR_DAY',
  CLEAR_WEEK: 'CLEAR_WEEK',
  LOAD_FROM_STORAGE: 'LOAD_FROM_STORAGE',
};